sdist build: (minor) exclude more stuff from tar.gz, rm git clean log
The `git clean --dry-run` became redundant with "fresh clone" builds.
The new exclude in MANIFEST.in should not affect production builds (also
due to fresh clone),
but they are nice when building from dirty local dir.

Backported from Electrum v4.1.0.

diff --git a/contrib/build-linux/sdist/make_tgz b/contrib/build-linux/sdist/make_tgz
--- a/contrib/build-linux/sdist/make_tgz
+++ b/contrib/build-linux/sdist/make_tgz
@@ -30,12 +30,8 @@ fi
 (
     cd "$ROOT_FOLDER"
 
-    echo "'git clean -fd' would delete the following files: >>>"
-    git clean -fd --dry-run
-    echo "<<<"
-
     # we could build the kivy atlas potentially?
-    #(cd electrum_nmc/electrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
+    #(cd contrib/android/; make theming) || echo "building kivy atlas failed! skipping."
 
     find -exec touch -h -d '2000-11-11T11:11:11+00:00' {} +
 
